kind: pipeline
type: kubernetes
name: default

steps:
  - name: echo
    image: alpine:latest
    commands:
      - echo "Hello World"

  - name: docker
    image: plugins/docker
    settings:
      registry: harbor.laecloud.com
      repo: harbor.laecloud.com/test/test
      use_cache: true
      username:
        from_secret: user
      password:
        from_secret: pass
    tags:
      - latest
    when:
      event: push
      branch: main

   - name: deploy
   steps:
- name: deploy
  image: harbor.laecloud.com/test/test
  settings:
    kubernetes_server: https://192.168.81.150:6443
    kubernetes_token: 
      from_secret: k8s_token
    namespace: test
    deployment: my-deployment
    repo: harbor.laecloud.com/test/test
    container: my-container
    tag: latest

image_pull_secrets:
- dockerconfigjson
