kind: pipeline
type: kubernetes
name: default

steps:
  - name: echo
    image: alpine:latest
    commands:
      - echo "Hello World"

  - name: docker
    image: plugins/docker
    settings:
      repo: harbor.laecloud.com/test/test
      use_cache: true
      username:
        from_secret: user
      password:
        from_secret: pass
    tags:
      - latest
    when:
      event: push
      branch: main

image_pull_secrets:
- dockerconfigjson
